config/routes.rb
require "resque/server"
require "resque-retry"
require "resque-retry/server"

WebTotem::Application.routes.draw do
  match "/find_cyclist"   => "cyclists#find",         as: :find_cyclist
  match "/authenticate"   => "cyclists#authenticate", as: :authenticate_cyclist
  match "/password"       => "cyclists#password",     as: :password
  match "/select_slot"    => "slots#select",          as: :select_slot
  match "/release_bike"   => "slots#release_bike",    as: :release_bike
  match "/releasing_bike" => "slots#releasing_bike"
  get   "/stations"       => 'stations#index'

  mount CompartbikeApi::Engine => "/"
  mount Resque::Server.new, at: "/resque"
  root to: "home#index"
end

app/models/cyclist.rb
class Cyclist < User
end

app/models/mechanical.rb
class Mechanical < User
end

app/models/remote_resource.rb
class RemoteResource < ActiveResource::Base
  self.site = Settings.server.path
  self.format = :json
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/compartbike_api.yml"
  namespace Rails.env
end

app/models/station.rb
class Station < RemoteResource
  self.include_root_in_json = false
end

app/models/user.rb
class User < RemoteResource

  def self.find_by_cpf(cpf)
    find(:one, from: "/#{self.to_s.downcase << 's'}/cpf.json?cpf=#{cpf}")
  rescue ArgumentError
    nil
  rescue
    :connection_error
  end
end

app/models/user_session.rb
class UserSession < RemoteResource
  def self.authenticate(login, password)
    create login: login, password: password
  rescue
    :connection_error
  end
end

app/controllers/application_controller.rb
#encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
    def error(message)
      flash[:error] = message
      redirect_to :back
    end

    def exceeded_tries?
      session[:tries] >= 3
    end

    def reset_tries!
      session[:tries] = 0
    end

    def increment_tries!
      session[:tries] += 1
    end
end

app/controllers/cyclists_controller.rb
# encoding: UTF-8
class CyclistsController < ApplicationController

  def find
    user = UserService.find(params[:cpf])

    if user.valid
      session[:login]          = user.login
      session[:cpf]            = user.cpf
      session[:is_mechanical?] = user.type == 'Mechanical'
      redirect_to password_path
    else
      redirect_to root_path, notice: user.message
    end
  end

  def password
    increment_tries!
  end

  def authenticate
    login = session[:login]
    password = params[:password]
    session = UserSession.authenticate(login, password)
    if session != :connection_error && session.persisted?
      reset_tries!

      redirect_to controller: :slots, action: :select
    elsif session == :connection_error
      error 'Erro de conexão. Tente novamente mais tarde.'
    else

      if exceeded_tries?
        redirect_to(root_path, notice: 'Tentativas Excedidas')
      else
        error 'Senha Invalida. Tente novamente!'
      end

    end
  end
end

app/controllers/home_controller.rb
# encoding: UTF-8
class HomeController < ApplicationController
  def index
    reset_tries!
    session[:login] 		 = nil
    session[:is_mechanical?] = nil
    flash[:notice]	= "Tempo de sessão esgotado. Retornando ao ínicio" if params[:timeout] && params[:timeout]=true
  end
end

app/controllers/slots_controller.rb
# encoding: UTF-8
class SlotsController < ApplicationController
  def select
    increment_tries!

    @slots = CompartbikeApi::Slot.order_by(:name.asc)
  end

  def release_bike
    slot_name        = view_context.api_slot_number(params[:slot_number].to_i)
    @slot            = CompartbikeApi::Slot.where(name: slot_name).first
    @role            = session[:is_mechanical?] ? 'mechanical' : 'cyclist'
    @release_manager = CompartbikeApi::ReleaseManager.new(@slot, session[:cpf], @role)

    if @release_manager.create_release
      more_options_or_releasing_path
    else
      redirect_to_error_or_exceeded
    end
  rescue
    redirect_to_error_or_exceeded
  end

  private
  def redirect_to_error_or_exceeded
    if exceeded_tries?
      redirect_to(root_path, notice: 'Tentativas Excedidas')
    else
      error "Baía inválida. Selecione outra baia."
    end
  end

  def more_options_or_releasing_path
    if session[:is_mechanical?]
      redirect_to select_slot_path, notice: 'Retire Outra Bicicleta ou Espere voltar para Página Inicial'
    else      
      render :releasing_bike
    end
  end
end

app/controllers/stations_controller.rb
# encoding: UTF-8
class StationsController < ApplicationController
  respond_to :json, :html

  def index
    @stations = Station.all

    respond_with(@stations)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for(:title){ text }
  end

  def has_bike?(slot)
    slot.state == "busy" && slot.sensor_status == "has_bike"
  end

  def user_slot_number slot
    fix_slot_number slot, "-"
  end

  def api_slot_number slot
    fix_slot_number slot, "+"
  end

  private

  # BUG: slot 10 and 17 are always broken,
  # so we skip the number 10 and 17 to 11 and 18
  def fix_slot_number(slot, method)
    slot = slot.send(method.to_sym, 1) if slot >= 10
    slot = slot.send(method.to_sym, 1) if slot >= 17
    slot
  end
end

app/views/cyclists/password.html.erb
<%= title "Entrar" %>
<div class="container content_area">
  <div id='cyclist' class="form">
    <div class="form_contact">    
      <div class="form-inputs">
        <%= render partial: 'layouts/message_after_enter_pressed', locals: { message: 'Autenticando...' } %>
        <%= form_tag authenticate_cyclist_path do %>
        </br>
        <div class="message_form">Informe sua senha</div>                
          <div class="block1">        
            <p>
              <label for="cyclist_password">* Senha: (4 números)</label>
              <input id="cyclist_password" name="password" size="30" type="password" autofocus="autofocus" />
            </p>
          </div>
        <% end %>
      </div>
    </div>  
</div>

app/views/home/index.html.erb
<%= title "Seja bem vindo ao Rivibike" %>
<div class="container content_area">
  <div id='cyclist' class="form">
    <div class="form_contact">    
      <div class="form-inputs">
        <%= render partial: 'layouts/message_after_enter_pressed', locals: { message: 'Procurando Usuário...' } %>
        <%= form_tag find_cyclist_path do %>
        </br>
        <div class="message_form">Informe seu CPF</div>
        
          <div class="block1">
            <p>
              <label for="cyclist_cpf">* CPF:</label>
              <input id="cyclist_cpf" name="cpf" size="30" type="text" autofocus="autofocus" />
            </p>
          </div>
        <% end %>
      </div>
    </div>  
</div>

app/views/layouts/_footer.html.erb
<div class="legend">
  <p> <strong class="red">ANULA</strong> = Voltar</p>
  <p> <strong class="green">ENTRA</strong> = Avançar</p>
</div>

app/views/layouts/_message_after_enter_pressed.html.erb
<p class='loader' data-need-to-check-pressed-enter='true' data-message='<%= message %>'>
  <span><%= image_tag('loader.gif') %></span>
  &nbsp;
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebTotem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascripts %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div style="height: 86px; display:inline-block; width: 191px; margin-top:10px; background-image:url('/assets/logorivi.png');"></div>
  <div class="title"><%= yield :title %></div>
</div>
<div class="container">
  <%= yield %>
  <p class="notice"><%= flash[:notice] unless flash[:error].present? %></p>
  <p class="error"><%= flash[:error] %></p>
</div>
<div class="footer">
  <%= content_for?(:footer) ? yield(:footer) : render(partial: 'layouts/footer') %>
</div>
</body>
</html>

app/views/slots/releasing_bike.html.erb
<%= title "Retirada" %>

<p class="retirement" data-timeout="7">Vá até a bicicleta escolhida aperte o botão e puxe a bicicleta para retirá-la. Você tem 1h gratuita para pedalar.</p>
</br>
<div class="bike"></div>

app/views/slots/select.html.erb
<%= title "Selecionar bicicleta" %>
<div class="container content_area">
  <div id='cyclist' class="form retirement_box">
    <div class="form_contact paddin">    
      <div class="form-inputs">
        <%= form_tag release_bike_path do %>
          <div class="select_bike">
            </br>        
            <p>
              <label for="slot_number">* Selecione uma bicicleta</label>
              <input id="slot_number" name="slot_number" size="20" type="text" autofocus="autofocus" />
            </p>
          </div>
        <% end %>
        <div class"bike_image_box">
          <%- @slots.each do |slot| %>
            <div class="image_bike">
              <%= image_tag has_bike?(slot) ? "bike_on.png" : "bike_off.png" %>
              <div class="number_bike"><%= user_slot_number(slot.name.to_i)%></div>
            </div>  
          <% end %>  
        </div>      
      </div>
    </div>  
</div>

app/views/stations/_footer.html.erb
<div class='legend maps'>
  <ul>
    <li>
      <p>(<strong>A</strong>) Mais Zoom</p>
      <p>(<strong>B</strong>) Menos Zoom</p>
    </li>
    <li>
      <% @stations.each do |station|%>
        <p>(<strong><%= station.station_number %></strong>) <%= station.name %></p>
      <% end %>
    </li>
  </ul>
</div>

app/views/stations/index.html.erb
<% content_for :javascripts do%>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <%= javascript_include_tag '/google-maps-utility/infobubble/src/infobubble' %>
<% end %>

<%= title "Mapa" %>

<section id='map_canvas' data-timeout=90></section>

<div id='hide-google-link'></div>

<% content_for :footer do%>
  <%= render partial: 'footer' %>
<% end %>